# Generated by Django 2.0.4 on 2018-06-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('t', 'Text'), ('u', 'Unicode')], default='u', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NameTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.TextField()),
                ('message', models.TextField()),
                ('service', models.CharField(choices=[('r', 'RouteSMS'), ('c', 'CLX')], default='r', help_text='Service to send', max_length=1)),
                ('type_text', models.CharField(choices=[('t', 'Text'), ('u', 'Unicode')], default='u', help_text='Format text', max_length=1)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodic_hour', models.IntegerField(default=0)),
                ('periodic_minutes', models.IntegerField(default=0)),
                ('planned_date', models.DateField(default=0)),
                ('planned_hour', models.IntegerField(default=0)),
                ('planned_minutes', models.IntegerField(default=0)),
                ('sms_key', models.CharField(default='', max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('message', models.TextField()),
                ('date_send', models.DateTimeField(default=django.utils.timezone.now)),
                ('sms_key', models.CharField(default='', max_length=100, unique=True)),
                ('smsList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SmsList')),
            ],
        ),
    ]
