# Generated by Django 2.0.4 on 2018-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstable',
            name='sms_key',
            field=models.CharField(default='0', max_length=100, unique=True),
        ),
    ]
