# Generated by Django 2.0.4 on 2018-06-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20180623_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smstable',
            name='sms_key',
        ),
    ]
