# Generated by Django 2.0.4 on 2018-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_template',
            name='type',
            field=models.CharField(choices=[('t', 'Text'), ('u', 'Unicode')], default='u', max_length=1),
        ),
    ]
