# Generated by Django 2.0.4 on 2018-04-09 22:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0004_message_template_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message_template',
            new_name='MessageTemplate',
        ),
        migrations.RenameModel(
            old_name='name_template',
            new_name='NameTemplate',
        ),
        migrations.RenameModel(
            old_name='list',
            new_name='SmsList',
        ),
    ]
